{
  "records":[
	{
		"id":1,
		"nom":"NAMDAR",
		"prenom":"Soheil",
		"mail":"soheilnamdar@yahoo.com",
		"residences":[
			{
				"id":1,
				"taille":100,
				"nbPiece":2,
				"equipments":[
								{
									"id":9
								},
								{
									"id":6
								}
							]
			},
			{
				"id":2,
				"taille":50,
				"nbPiece":3,
				"equipments":[
								{
									"id":7
								},
								{
									"id":10
								}
							]
			}
		]
	},
	{
		"id":2,
		"nom":"NAMDAR",
		"prenom":"Sepehr",
		"mail":"sepehr@yahoo.com",
		"residences":[
						{
							"id":3,
							"taille":110,
							"nbPiece":3,
							"equipments":[
											{
												"id":9
											},
											{
												"id":6
												}
										]
						}
					]
	},
		
	{
		"id":3,
		"nom":"WORLD",
		"prenom":"john",
		"mail":"worldjohn@hotmail.fr",
		"residences":[
						{
							"id":4,
							"taille":40,
							"nbPiece":1,
							"equipments":[
											{
												"id":7
											},
											{
												"id":10
											},
											{
												"id":9
											}
										]
						}
					]
	},

	{
		"id":4,
		"nom":"DUPONT",
		"prenom":"Olivier",
		"mail":"olivierDupont@yahoo.fr",
		"residences":[
						{
							"id":5,
							"taille":15,
							"nbPiece":1,
							"equipments":[
											{
												"id":10
											}
										]
						}
					]
	}
  ]
}